#!/bin/bash

# exiftran-rotation: si possible, effectue une rotation automatique et sans perte de qualité d'une image JPG. La rotation à effectuer est trouvée à partir de l'orientation déclarée dans les données Exif, si cette information existe.

# Auteur: Jean-Philippe Fleury <contact@jpfleury.net>
# Copyright © Jean-Philippe Fleury, 2010.

# Ce programme est un logiciel libre; vous pouvez le redistribuer ou le
# modifier suivant les termes de la GNU General Public License telle que
# publiée par la Free Software Foundation: soit la version 3 de cette
# licence, soit (à votre gré) toute version ultérieure.

# Ce programme est distribué dans l'espoir qu'il vous sera utile, mais SANS
# AUCUNE GARANTIE: sans même la garantie implicite de COMMERCIALISABILITÉ
# ni d'ADÉQUATION À UN OBJECTIF PARTICULIER. Consultez la Licence publique
# générale GNU pour plus de détails.

# Vous devriez avoir reçu une copie de la Licence publique générale GNU avec
# ce programme; si ce n'est pas le cas, consultez
# <http://www.gnu.org/licenses/>.

# Merci à <http://stackoverflow.com/questions/592620/check-if-a-program-exists-from-a-bash-script/677212#677212>.
type -P exiftran &>/dev/null || { zenity --error --text="exiftran n'est pas installé. Fin du script." >&2; exit 1; }

printf %s "$NAUTILUS_SCRIPT_SELECTED_FILE_PATHS" |
(
	messagesScript=''
	
	while read -r image; do
		typeMime=$(file --mime-type "$image" | rev | cut -d ' ' -f1 | rev)
		
		if [ $typeMime == 'image/jpeg' ]; then
			exiftran -aip "$image"
			messagesScript="$messagesScript$image\n"
		fi
	done
	
	zenity --info --text="Rotation automatique terminée:\n\n$messagesScript"
)
